name: ViaOps CI
on:
  push:
    branches: [main]

  # schedule: deve utilizar quando for necessário agendamendo para execução
  # run at *minute  *hours *month *months of the years *days of week
  # - cron: "* * * * *"

  workflow_dispatch:
   
jobs:
  cypress-run-tests:
    name: Cypress run
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.5
        with:
          node-version: ${{ matrix.node-version }}
      
      - run: npm install

      - name: Cypress run tests
        uses: cypress-io/github-action@v4
        with:
          command: npx cypress run
        env:
          CYPRESS_password: ${{ secrets.PASSWORD }}
