name: ViaOps CI
on:
  push:
    branches: [main]

  workflow_dispatch:
    inputs:
      amb:
        description: "Selecionar algum destes ambientes: dev / stg / hlg / prd"
        required: false
        default: "qa"
      browser:
        description: "Selecionar algum destes browsers: chrome / electron"
        require: true
        default: "chrome"

env:
  DEFAULT_KEY: "7df7b9e7-1575-489f-8aa2-e7bc49c33670"
  DEFAULT_AMB: "qa"
  DEFAULT_BROWSER: "chrome"
  DEFAULT_TAG: "@demo"
  DEFAULT_GROUP: "CI"

jobs:
  cypress-run-tests:
    name: Cypress run
    runs-on: ubuntu-latest
    container: cypress/browsers:node14.17.6-chrome100-ff98
    strategy:
      fail-fast: false
      matrix:
        containers: [1, 1, 3, 4]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cypress run tests
        uses: cypress-io/github-action@v4
        with:
          command: npx cypress run --record --parallel --group ${{env.DEFAULT_GROUP}} --key ${{env.DEFAULT_KEY}} --browser ${{github.event.inputs.browser || env.DEFAULT_BROWSER}} --env version=${{github.event.inputs.amb || env.DEFAULT_AMB}}
        env:
          CYPRESS_password: ${{ secrets.PASSWORD }}

      - name: Generate Allure Report
        uses: simple-elf/allure-report-action@master
        if: always()
        with:
          allure_results: allure-results
          allure_history: allure-history
          keep_reports: 20

      - name: Deploy report to Github Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v2
        env:
          PERSONAL_TOKEN: ${{ secrets.ACTIONS_TOKEN }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: allure-history
